version: "3"

services:
  crawl:
    image: gpu_crawler:0.9
    build: .
    volumes: 
      - .:/home/gpu_crawler
    # Set AWS IAM credentials here to be passed into docker container
    environment:
      - AWS_ACCESS_KEY_ID= <access-key-id>
      - AWS_SECRET_ACCESS_KEY= <secret-access>
      - AWS_REGION= "us-west-2"
    # Add desired phone number as 16674443232
    command: >
      bash -c "python3 crawler.py <phone-number-here>"

